 - name: Stop Service for patching
   import_tasks: Stop_Service.yml

 - name: Patch installation
   import_tasks: Patch_Installation.yml

 - name: patching Confirmation
   import_tasks: Patch_Confirmation.yml

 - name: Restart Services
   import_tasks: Restart_Services.yml