 - name : Code with error handling
   block : 
    - name : Restart Services
      ansible.builtin.systemd:
        name : "{{ item }}"
        state: restarted
      ignore_errors: true
      # register: "stop_service_variable"
      loop : "{{services_name}}"

   rescue:
      - name: Restart service forcefully
        debug:
          msg : "Failed to restart services"
