 - name : Code with error handling
   block : 
    - name : Restart Services
      ansible.builtin.systemd:
        name : "{{ item }}"
        state: stopped
      ignore_errors: true
      loop : "{{services_name}}"
      
   rescue:
      - name: Restart service forcefully
        debug:
          msg : "Failed to restart services"
