 - name : Code with error handling
   block : 
      - name : Stop Services
        ansible.builtin.service:
          name : "{{ item }}"
          state: stopped
        loop: "{{services_name}}"
 
   rescue:
        - name: stop srevice forcefully
          debug:
            msg : "Failed to stop services"









# register : stop_service_variable
          # content : "{{stop_service_variable.stdout}}"
          # dest : "{{patch_var}}//stop_service.log"
























































# - name : Stop Services
      #   ansible.builtin.service:
      #     name : "{{services_name[1]}}"
      #     state : stopped