- name : Code with error handling
  block : 
  - name : Convert folder into zip
    ansible.builtin.archive:
      path: "{{Comman_path2}}"
      dest: "{{Comman_path2}}.patch.zip"            
  


  - name : Delete file in folder after converting folder into zip
    ansible.builtin.file: 
      state: absent 
      path: "{{Comman_path2}}"

  rescue:
      - name: Print resue block
        debug:
          msg : "Failed to CleanUp"

   