- name: Example playbook sending mail to root
  community.general.mail:
    subject: System {{ ansible_hostname }} has been successfully provisioned.
  delegate_to: localhost

- name: Sending an e-mail using Gmail SMTP servers
  community.general.mail:
    host: Notification[host_name]
    port: Notification[port_no]
    username: Notification[user]
    password: Notification[password]
    to: Notification[detail]
    subject: Notification[sub]
  delegate_to: localhost