
- name: Resources_health_check for ****** Post patching *******************
  block:
    - name: Resources_health_check
      include_role: 
        name: pre-patching
        tasks_from: Verify_resources.yml
  vars:
    Stage_dir: "{{Stage_dir2}}"

  rescue:
      - name: Print resue block
        debug:
          msg : "Failed Resource_Helth_Check"