- name : Code with error handling
  block : 
    - name : Create  Directory
      ansible.builtin.file:
        path : "{{Comman_path}}/{{Stage_dir}}"
        state : directory

  rescue:
      - name: Print resue block
        debug:
          msg : "Failed to create folder"

  