# Step 4 : Gather Evidences
- name: Code to display Error handling
  block : 

    - name: List upgradable packages
      ansible.builtin.shell:
        cmd : apt list --upgradable 
      register: apt_updates
      changed_when: false

    - name : To store upgrade package in file
      ansible.builtin.copy:
        content : "{{apt_updates.stdout}}"
        dest : "{{pre_patch_var}}//pre-patch3.log"

  rescue : 
    - name : print rescue block 
      debug : 
        msg : "Failed to gather Facts"