- name : Code with error handling
  block : 
    - name: Display all running services
      ansible.builtin.command:
        cmd : systemctl list-units --type=service
      register : my_var

    - name : To store running service in file
      ansible.builtin.copy:
        content : "{{my_var.stdout}}"
        dest : "{{Comman_path}}/{{Stage_dir}}/gather_active_services.log"       

  rescue : 
    - name : Print resue block
      debug : 
        msg : "Failed to display running services"