- name : Convert folder into zip
  ansible.builtin.archive:
    path: "{{Comman_path}}/{{Stage_dir}}"
    dest: "{{Comman_path}}/{{Stage_dir}}.prepatch.zip"            
    format: zip
    owner: root
    group: root
    mode: '644'
    